import Head from "next/head";
import Image from "next/image";
import { Playfair_Display } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navigation from "../components/navigation";
import Banner from "../components/banner";
import ArticleCard from "../components/articlecard";
import Photo from "../images/cardImage.jpg";
import Photo2 from "../images/home-banner.jpg";
import Link from "next/link";
import { useRouter } from "next/router";
import Footer from "../components/footer";

const data = [
  {
    id: 1,
    category: "Traveling",
    image: "https://picsum.photos/id/230/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  {
    id: 2,
    category: "Traveling",
    image: "https://picsum.photos/id/229/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  {
    id: 3,
    category: "Traveling",
    image: "https://picsum.photos/id/228/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  {
    id: 4,
    category: "Traveling",
    // image: "https://picsum.photos/id/227/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  {
    id: 5,
    category: "Traveling",
    image: "https://picsum.photos/id/225/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts 50",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  ,
  {
    id: 6,
    category: "Traveling",
    image: "https://picsum.photos/id/223/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts 50",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },

  {
    id: 7,
    category: "Traveling",
    image: "https://picsum.photos/id/221/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts 50",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  {
    id: 8,
    category: "Traveling",
    image: "https://picsum.photos/id/220/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts 50",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  {
    id: 9,
    category: "Traveling",
    // image: "https://picsum.photos/id/219/200/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts 50",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
  {
    id: 10,
    category: "Traveling",
    image: "https://picsum.photos/id/218/199/300",
    date: "December 22th,2022",
    title: "Astonishing Facts About The Greek Resorts 50",
    content:
      "You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion...",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>ALIFYA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-44">
        <Navigation />
        <Banner />
        <div className="grid px-3   md:grid-rows-3 md:grid-cols-4 md:grid-flow-col gap-5 items-center justify-center mt-5 md:px-32 ">
          {data.map((art) => (
            <ArticleCard
              key={art.id}
              href={`blog/${art.title}`}
              category={art.category}
              image={art.image}
              date={art.date}
              title={art.title}
              content={art.content}
            />
          ))}
        </div>
      </main>
      <Footer />
    </>
  );
}
